import re
import streamlit as st
from dotenv import load_dotenv
from crewai import Agent, Task, Crew
from crewai.tools import tool
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_community.tools import DuckDuckGoSearchRun

from agent_loader import get_agent_config
from youtube_analytics_tool import youtube_analytics_tool
from history_tool import (
    history_tool, save_run, link_video, list_unlinked_runs,
)

load_dotenv()

st.set_page_config(page_title="AI Empire - 11 Agents", page_icon="👑", layout="wide")
st.title("👑 The 11-Agent Content Factory")
st.markdown(
    "Βάλε το θέμα σου και άσε τους 11 agents (μαζί με τον **Performance Strategist** "
    "που διαβάζει τα YouTube Analytics σου) να σου φτιάξουν ολόκληρο content package."
)

# --- Models & Tools ---
manager_llm = ChatGoogleGenerativeAI(model="gemini-3.1-pro-preview")
worker_llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash")
search_tool_raw = DuckDuckGoSearchRun()

@tool("internet_search")
def search_tool(query: str):
    """Ψάχνει στο internet για ειδήσεις."""
    return search_tool_raw.run(query)


# ==========================================
# SIDEBAR: Link a Published Video
# ==========================================
st.sidebar.header("🔗 Link a Published Video")
st.sidebar.markdown(
    "After you publish a video that was generated by this tool, "
    "link it here so the Strategist can learn from its performance."
)

unlinked = list_unlinked_runs()
if unlinked:
    run_options = {f"{r['created_at'][:10]} - {r['topic']}" : r['id'] for r in unlinked}
    selected_label = st.sidebar.selectbox("Select a run:", list(run_options.keys()))
    video_id_input = st.sidebar.text_input("YouTube Video ID (e.g. dQw4w9WgXcQ):")
    if st.sidebar.button("Link Video"):
        if video_id_input.strip():
            success = link_video(run_options[selected_label], video_id_input.strip())
            if success:
                st.sidebar.success(f"Linked! The Strategist will use this data next time.")
            else:
                st.sidebar.error("Run not found.")
        else:
            st.sidebar.warning("Please enter a video ID.")
else:
    st.sidebar.info("No unlinked runs yet. Generate some content first!")


# ==========================================
# MAIN: Content Generation
# ==========================================
topic = st.text_input(
    "Για ποιο θέμα θέλεις να ψάξουν; (π.χ. AI News, Crypto, Tesla, Gaming)",
    value="AI News",
)

if st.button("🚀 Ξεκίνα την Παραγωγή!", type="primary"):
    with st.spinner("Η στρατιά των 11 Agents δουλεύει... (αυτό μπορεί να πάρει 3-5 λεπτά)"):

        # --- Load all agent configs from YAML ---
        agent_names = [
            'performance_strategist', 'trend_hunter', 'scriptwriter',
            'title_master', 'visual_director', 'video_editor',
            'thumbnail_designer', 'seo_expert', 'social_media_manager',
            'voiceover_coach', 'general_manager',
        ]
        cfgs = {}
        for name in agent_names:
            kwargs = {'topic': topic} if name == 'trend_hunter' else {}
            cfgs[name] = get_agent_config(name, **kwargs)

        # --- 11 Agents ---
        a = {}
        a['strategist'] = Agent(
            role=cfgs['performance_strategist']['role'],
            goal=cfgs['performance_strategist']['goal'],
            backstory=cfgs['performance_strategist']['backstory'],
            tools=[youtube_analytics_tool, history_tool],
            llm=manager_llm, verbose=False, allow_delegation=False,
        )
        a['hunter'] = Agent(
            role=cfgs['trend_hunter']['role'],
            goal=cfgs['trend_hunter']['goal'],
            backstory=cfgs['trend_hunter']['backstory'],
            tools=[search_tool],
            llm=worker_llm, verbose=False, allow_delegation=False,
        )
        a['writer'] = Agent(
            role=cfgs['scriptwriter']['role'],
            goal=cfgs['scriptwriter']['goal'],
            backstory=cfgs['scriptwriter']['backstory'],
            llm=worker_llm, verbose=False, allow_delegation=False,
        )
        a['titles'] = Agent(
            role=cfgs['title_master']['role'],
            goal=cfgs['title_master']['goal'],
            backstory=cfgs['title_master']['backstory'],
            llm=worker_llm, verbose=False, allow_delegation=False,
        )
        a['visual'] = Agent(
            role=cfgs['visual_director']['role'],
            goal=cfgs['visual_director']['goal'],
            backstory=cfgs['visual_director']['backstory'],
            llm=worker_llm, verbose=False, allow_delegation=False,
        )
        a['editor'] = Agent(
            role=cfgs['video_editor']['role'],
            goal=cfgs['video_editor']['goal'],
            backstory=cfgs['video_editor']['backstory'],
            llm=worker_llm, verbose=False, allow_delegation=False,
        )
        a['thumb'] = Agent(
            role=cfgs['thumbnail_designer']['role'],
            goal=cfgs['thumbnail_designer']['goal'],
            backstory=cfgs['thumbnail_designer']['backstory'],
            llm=worker_llm, verbose=False, allow_delegation=False,
        )
        a['seo'] = Agent(
            role=cfgs['seo_expert']['role'],
            goal=cfgs['seo_expert']['goal'],
            backstory=cfgs['seo_expert']['backstory'],
            llm=worker_llm, verbose=False, allow_delegation=False,
        )
        a['social'] = Agent(
            role=cfgs['social_media_manager']['role'],
            goal=cfgs['social_media_manager']['goal'],
            backstory=cfgs['social_media_manager']['backstory'],
            llm=worker_llm, verbose=False, allow_delegation=False,
        )
        a['voice'] = Agent(
            role=cfgs['voiceover_coach']['role'],
            goal=cfgs['voiceover_coach']['goal'],
            backstory=cfgs['voiceover_coach']['backstory'],
            llm=worker_llm, verbose=False, allow_delegation=False,
        )
        a['gm'] = Agent(
            role=cfgs['general_manager']['role'],
            goal=cfgs['general_manager']['goal'],
            backstory=cfgs['general_manager']['backstory'],
            llm=worker_llm, verbose=False, allow_delegation=False,
        )

        # --- 11 Tasks ---
        t0 = Task(
            description=(
                'Χρησιμοποίησε τα tools youtube_analytics και production_history. '
                'Βγάλε ένα Viral Strategy Brief.'
            ),
            expected_output='Viral Strategy Brief (5-10 γραμμές).',
            agent=a['strategist'],
        )
        t1 = Task(
            description=f'Ακολούθησε τη στρατηγική. Βρες είδηση για: {topic}.',
            expected_output='Περίληψη, link, και γιατί ταιριάζει στη στρατηγική.',
            agent=a['hunter'], context=[t0],
        )
        t2 = Task(
            description=(
                'Γράψε σενάριο 60 δευτερολέπτων χωρισμένο σε 6 Scenes. '
                '[Scene 1]: Δυνατό Hook | [Scene 2-5]: Κείμενο | [Scene 6]: CTA'
            ),
            expected_output='Σενάριο 6 σκηνών.',
            agent=a['writer'], context=[t0, t1],
        )
        t3 = Task(
            description='Φτιάξε 5 clickbait τίτλους.',
            expected_output='5 τίτλοι.',
            agent=a['titles'], context=[t0, t1],
        )
        t4 = Task(
            description='Φτιάξε 3 αγγλικά image prompts.',
            expected_output='3 Image Prompts.',
            agent=a['visual'], context=[t2],
        )
        t5 = Task(
            description='Γράψε οδηγίες μοντάζ ανά Scene.',
            expected_output='Οδηγίες Editor.',
            agent=a['editor'], context=[t2],
        )
        t6 = Task(
            description='Στήσε το Thumbnail brief.',
            expected_output='Thumbnail brief.',
            agent=a['thumb'], context=[t3],
        )
        t7 = Task(
            description='Γράψε YouTube Description και hashtags.',
            expected_output='SEO Description & Tags.',
            agent=a['seo'], context=[t3, t2],
        )
        t8 = Task(
            description='Γράψε TikTok/Insta caption και Twitter post.',
            expected_output='Social captions.',
            agent=a['social'], context=[t3],
        )
        t9 = Task(
            description='Δώσε οδηγίες voiceover (τόνος, ρυθμός, παύσεις).',
            expected_output='Voiceover direction.',
            agent=a['voice'], context=[t2],
        )
        t10 = Task(
            description=(
                'Μάζεψε ΟΛΑ τα outputs. Φτιάξε ένα Master Document σε Markdown:\n'
                '1. "🎬 FLIKI SCRIPT" - μόνο το κείμενο χωρίς [Scene X]\n'
                '2. Strategy Brief\n'
                '3. Titles\n'
                '4. Image Prompts\n'
                '5. Edit Notes\n'
                '6. Thumbnail Brief\n'
                '7. SEO\n'
                '8. Social Captions\n'
                '9. Voiceover Direction'
            ),
            expected_output='Τελικό Master Document έτοιμο για Copy-Paste.',
            agent=a['gm'],
            context=[t0, t1, t2, t3, t4, t5, t6, t7, t8, t9],
        )

        # --- Crew ---
        all_agents = list(a.values())
        all_tasks = [t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10]

        crew = Crew(
            agents=all_agents,
            tasks=all_tasks,
            max_rpm=3,
            verbose=False,
        )

        result = crew.kickoff()

    # --- Display Result ---
    st.success("👑 Η Αυτοκρατορία σου μίλησε! Το Content Package είναι έτοιμο.")
    st.markdown(result.raw)

    # --- Save to Production History ---
    raw_output = result.raw if hasattr(result, 'raw') else str(result)

    hook_match = re.search(
        r'(?:\[HOOK\]|\[Scene 1\])[:\s]*\n?(.*?)(?:\n\n|\[(?:BODY|Scene 2)\])',
        raw_output, re.DOTALL,
    )
    hook = hook_match.group(1).strip() if hook_match else raw_output[:120]

    strategy_output = t0.output.raw if t0.output else "N/A"

    run_id = save_run(
        topic=topic,
        strategy_brief=strategy_output[:500],
        hook=hook,
        script_summary=raw_output[:300],
        titles=[],
    )

    st.info(f"📝 Run saved (ID: `{run_id}`). After publishing, link the video in the sidebar!")